### PR TITLE
Use pibooth logger instead of custom config value

### PR DESCRIPTION
**Pull request by anxuae**
- Rework logging messages to avoid custom config key in configuration file
- Rename config key prefix  `db_` because already in a section dedicated to Dropbox
- Replace custom function `stopwatch` by `timeit`

### CODE REVIEW

**Comment by anxuae** [comment]
Maybe it is not necessary to call the function `get_config_options`? Only `album_name` can be changed dynamically. @mhilcher what do you think?

**Comment by mhilcher** [comment]
> Maybe it is not necessary to call the function `get_config_options`? Only `album_name` can be changed dynamically. @mhilcher what do you think?

I was thinking about allow to change more options dynamically. The first version was just for me and I know how to use config files. But what if a not so skilled user wants to use it and it should be running "out of the box". Then maybe it could be necessary to change the config during runtime. 

You are right, now, that the Debug option is gone, there is just the album name.
For me the possibility to change the debug option during runtime was a comfortable function for debugging when I ran into an error, e.g. with the dropbox token.

For me the changes you suggest are ok, I can live with that as I am done with coding and debugging of the first version and I'm looking forward to how the code can be improved.

**Comment by mhilcher** [comment]
By the way: This looks very professional and I am glad that the code is now in the hands of the pibooth organization.
Thank you.

**Comment by anxuae** [comment]
@mhilcher thanks for your feedback. debug logs can be seen when starting pibooth with `-v` option.
But I keep in mind the possibility to change log level dynamically, I think this should be an option developed in `pibooth` core

**Pull request merged**
